name: DebugBuild
on:
  push:
    branches:
     -master
env:
 SOLUTION_FILE_PATH: Project/GE3_sin
 CONFIGURATION: Debug
 jobs:
  build:
    runs-on:windows-2022
  steps:
    -name: Checkout
    uses: actions/checkout@v4
    -name: Add MSBuil to PATH
    uses: microsoft/setup-msbuil@v2
  with:
      msbuil-architecture: x64
    -name: Build
    run:
      msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
